# -*- coding: utf-8 -*-
"""img loading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JsvYQXzUuv-TEnUVanFb-2gTlzsKZJs4
"""

import cv2
from google.colab.patches import cv2_imshow

# Load an image from file
image = cv2.imread('/content/21.png')

# Check if the image was loaded successfully
if image is None:
    print("Error: Could not load image.")
else:
    # Display the image (use cv2_imshow in Colab)
    cv2_imshow(image)

